version: '3'
services:
  robotmapapi:
    build: ./RobotMapAPI
    container_name: robotmapapi
    networks:
      - backend
    restart: on-failure
    ports:
      - "3000:3000"
      - "3001:3001"

  robotmapclient:
    build: ./RobotMapClient
    container_name: robotmapclient
    networks:
      - backend
    restart: on-failure
    depends_on:
      - robotmapapi
    ports:
      - "80:80"
networks:
  backend: